const { TreeNode, hasPathSum } = require('./solution')

test('hasPathSum', () => {
  const root = new TreeNode(5)
  root.left = new TreeNode(4)
  root.right = new TreeNode(8)
  root.left.left = new TreeNode(11)
  root.left.left.left = new TreeNode(7)
  root.left.left.right = new TreeNode(2)
  root.right.left = new TreeNode(13)
  root.right.right = new TreeNode(4)
  root.right.right.right = new TreeNode(1)
  expect(hasPathSum(root, 22)).toBe(true)
  expect(hasPathSum(root, 26)).toBe(true)
  expect(hasPathSum(root, 27)).toBe(true)
})
